config/routes.rb
Rails.application.routes.draw do

root 'main#index'

resources :main
get 'show_graph' => 'main#show_graph'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
	include ActionView::Helpers::NumberHelper
	
	has_many :payments, dependent: :destroy
	validates_presence_of :name, :last_name, :phone, :email, :personal_id, :credit_sum
	before_save :calculate_graph

	def calculate_graph
		credit_start_date = loan_start_date

		credit_intress = 0.1

		# monhtly payment
		year_percent = credit_intress / 12 
		rank = ( 1 + year_percent )**credit_period - 1
		monthly_payment = credit_sum * ( year_percent + (year_percent / rank))

		intress_payment = monthly_payment * credit_period - credit_sum
		# percent payment
		percent = credit_sum * year_percent
		# balance 
		balance = credit_sum
		# main part of payment
		principal_repayment	= monthly_payment - percent
		
		
		credit_period.times do
			
			credit_start_date = credit_start_date + 1.month

			payments.build({
				payment_date: credit_start_date.strftime('%d.%m.%Y'),
				monthly_paymnet_total: number_to_currency(monthly_payment, precision: 2, :unit => "", :delimiter => ""),
				payment_balance: number_to_currency(balance, precision: 2, :unit => "", :delimiter => ""),
				intress_payment: number_to_currency(percent, precision: 2, :unit => "", :delimiter => ""),
				princial_repayment: number_to_currency(principal_repayment, precision: 2, :unit => "", :delimiter => "")
			})

			# Recounting with new balance
			balance -= principal_repayment
			percent = balance * year_percent
			principal_repayment = monthly_payment - percent

		end

		return payments	
	end

	def loan_start_date
		DateTime.now
	end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :loan
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		@new_loan = Loan.new
		@loans = Loan.all
	end

	def create
		@new_loan = Loan.new loan_params

		@new_loan.credit_start_date = DateTime.now

		if @new_loan.save
			redirect_to :back
		else
			render :index		
		end

	end
	
	def show
		@loan = Loan.find(params[:id])
		@payments = @loan.payments
	end

	def destroy
		@loan = Loan.find(params[:id])
		@loan.destroy

		redirect_to :back
	end
	
	def show_graph
		@new_loan = Loan.new loan_params
		@new_loan.calculate_graph
		render :json => @new_loan.to_json({:include => :payments})
	end

	def loan_params
		params.require(:loan).permit(:name,:last_name,:email,:phone,:personal_id,:credit_sum,:credit_period,:credit_start_date)
	end

end
# amount

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LoanCalculator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/_loan_form.html.erb
<%= simple_form_for @new_loan, :url => main_index_path , method: :post do |f|%>
        
  <h4>Personal <small>information</small></h4>
  <hr>

  <div class="form-group form-inline">
    <%= f.input :name, placeholder: 'Name', label: false, class: "form-control" %>
    <%= f.input :last_name, placeholder: 'Last Name', label: false, class: "form-control" %>
  </div>

  <div class="form-group form-inline">
    <%= f.input :phone, placeholder: 'Phone', label: false, class: "form-control" %>
    <%= f.input :personal_id, placeholder: 'Personal ID', label: false, class: "form-control" %>  
  </div>

  <div class="form-group">
    <%= f.input :email, placeholder: 'Email', label: false, class: "form-control" %>
  </div>
  
  <div class="page-header">
    <h4>Loan <small>information</small></h4>
  </div>

  <div class="form-group form-inline">
    <%= f.input :credit_sum, placeholder: "Loan amount", label: false, class: "form-control", :input_html => { :value => '300'}%>
    
    <%= f.select(:credit_period, options_for_select([['6 months',6],['1 year',12],['2 years',24],['3 years',36],['4 years',48],['5 years',60]], :selected => params[:credit_period]), {}, class: "form-control" )%>
    <input type="text" placeholder="10%" class="form-control" style="width:75px"disabled>
  </div>
  
  <hr>
  <%= f.submit 'Confirm' ,class: 'btn btn-success pull-right' %>
  
  <btn class="btn btn-primary">Show payments graphic</btn>
<% end %>

app/views/main/_loan_graphic.html.erb
<table class="table table-bordered" id="payments_table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Balance</th>
      <th>Principal repayment </th>
      <th>Interest payment </th>
      <th>Month payment</th>
    </tr>
  </thead>
  <tbody id="payments_tbody">
            
  </tbody>
  <tfoot></tfoot>    
</table>

app/views/main/_loans_table.html.erb
<div class="col-md-12">
  <h3>Loans</h3>
  <hr>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Loan Amount</th>
        <th>Loan period</th>
        <th>Loan start date</th>
      </tr>
    </thead>  
    <tbody>
      <% @loans.each do |l| %>
        <tr>
          <td><%= l.name %></td>
          <td><%= l.credit_sum %></td>
          <td><%= l.credit_period %> months</td>
          <td><%= l.credit_start_date %></td>
          <td>
            <%= link_to main_path(l) do %>
              <span class="btn btn-info">
                <i class="fa fa-search"></i>  
              </span>
            <% end %>
          </td>
          <td>
            <%= link_to main_path(l),:method => :delete do %>
              <span class="btn btn-danger">
                <i class="fa fa-times"></i>
              </span>
            <% end %>
          </td>
        </tr>
      <% end %>    
    </tbody>
  </table>
</div>

app/views/main/index.html.erb
<div class="container">
  <div class="row">
    <hr>
    <div class="col-md-4 well">
      <%= render 'loan_form' %>
    </div>

    <div class="col-md-7 col-md-offset-1 well payments_graphic">
      <h3>Payments <small>graph</small></h3>
      <hr>
      <%= render 'loan_graphic' %>
    </div>
    <% unless @loans.blank? %>
      <%= render 'loans_table' %>
    <% end %>
  
  </div>  
</div>

app/views/main/show.html.erb
<div class="container">
  <div class="row">
    <h3>Payments <small>graph</small></h3>
    <hr>
    <div class="col-md-9 well">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Payment date</th>
            <th>Payment balance</th>
            <th>Princial repayment</th>
            <th>Intress payment</th>
            <th>Monthly paymnet total</th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |p| %>
            <tr>
              <td><%= p.payment_date.strftime('%d.%m.%Y') %></td>
              <td><%= p.payment_balance %></td>
              <td><%= p.princial_repayment %></td>
              <td><%= p.intress_payment %></td>
              <td><%= p.monthly_paymnet_total %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>